### PR TITLE
`deltas()` function, closes #437

### LINKED ISSUE #437: New method: `deltas()`
When working on the [gamut mapping playground](https://colorjs.io/apps/gamut-mapping) recently, I needed to calculate deltas in OKLCh (differences per component) and ended up doing so by hand.

This seems like a more generally useful function. We have `distance()` and a bunch of `deltaE()` methods, but nothing that is done per-component.

What do you think?

### PR DESCRIPTION
**Pull request by LeaVerou**

### CODE REVIEW

**Comment by facelessuser** [comment]
Shouldn't this have special handling for hues?

**Comment by svgeesus** [comment]
> Shouldn't this have special handling for hues?

Yes, [as I said earlier](https://github.com/color-js/color.js/issues/437#issuecomment-2002152896)

**Review by svgeesus — CHANGES_REQUESTED** [review]
Needs to calculate delta of the hue arc, not the angular delta

**Comment by LeaVerou** [comment]
I envisioned this as a low-level utility function, if users want to make this optimization for hue it's trivial to do so on the deltas returned. 

That said, it should probably constrain the ΔH returned (possibly by also preserving the original).

**Comment by LeaVerou** [comment]
Ok, I’ve made several improvements:
- A hue interpolation setting, with `"shorter"` being the default.
- Fixed a bunch of issues around `none` handling, and added more tests.

**Comment by LeaVerou** [comment]
We could have another option for scaling the Δh by taking C/L into account, but not sure how that would work in a generic way.

**Comment by facelessuser** [comment]
Looks good to me. I would fix lint issues. related to the files in questions.

**Review by facelessuser — APPROVED** [review]
LGTM

**Pull request merged**
