### PR TITLE
Remove duplicates and mentions of tiny PRs

### PR DESCRIPTION
**Pull request by DmitrySharabin**
Those are the changes to the list at the end of the release notes.

### CODE REVIEW

**Review by LeaVerou — CHANGES_REQUESTED** [review]
I would tend to just group these under larger items (e.g. there's one for improving types) because you still want to give the appropriate credit to people.

**Comment by DmitrySharabin** [comment]
I moved the PRs in the sections they belong to (from my perspective). Please take a look.

**Comment by facelessuser** [comment]
I think I'm generally okay with the consolidations here, but I do believe that unique bugs need to be called out specifically for those experiencing issues and want to know the issue has been resolved. So with that said, I think https://github.com/color-js/color.js/pull/575 should be called out under fixes as it resolves the issue noted here: https://github.com/color-js/color.js/issues/553, which is a real issue that could affect users.

**Comment by LeaVerou** [comment]
> I think I'm generally okay with the consolidations here, but I do believe that unique bugs need to be called out specifically for those experiencing issues and want to know the issue has been resolved. So with that said, I think #575 should be called out under fixes as it resolves the issue noted here: #553, which is a real issue that could affect users.

Agreed, under a "Bugfixes" section

**Review by LeaVerou — CHANGES_REQUESTED** [review]
Thanks! Almost there, see feedback by @facelessuser

**Comment by DmitrySharabin** [comment]
@facelessuser @LeaVerou Thank you so much for your review. I tried to address your feedback. Could you please take another look?

**Review by LeaVerou — APPROVED** [review]
LGTM though let's wait a day or two in case anyone else sees issues

**Review by lloydk — APPROVED** [review]
LGTM

**Review by facelessuser — APPROVED** [review]

**Comment by facelessuser** [comment]
LGTM

**Pull request merged**
