### PR TITLE
Allow angle values for HCT Hue coordinate

### PR DESCRIPTION
**Pull request by lloydk**
Allow angle values for HCT Hue coordinate.

### CODE REVIEW

**Review by LeaVerou — APPROVED** [review]

**Comment by LeaVerou** [comment]
Gah, approved too soon. Could you please add that parse test to the actual testsuite? The old testsuite is only there for historical reasons.

**Comment by lloydk** [comment]
> Gah, approved too soon. Could you please add that parse test to the actual testsuite? The old testsuite is only there for historical reasons.

If the parse tests were ported I would have added them to that suite. 

If you want to hold off on merging until there's a parse test suite in the new format I'm fine with that.

**Comment by lloydk** [comment]
I guess you already merged it, wasn't paying attention.

**Comment by LeaVerou** [comment]
Ah ok, I guess it makes sense then.

**Pull request merged**
